### PR TITLE
A11y: Table tds not selectable.

### PR DESCRIPTION
**Pull request by microbit-carlos**
Removing the td field from the querySelector, and converting the snippet triggers into a link.

### CODE REVIEW

**Comment by microbit-mark** [comment]
Tested in Chrome and Safari, but this breaks snippets in Firefox. Not sure why. TBH tabbing doesn;t work propery in FF anyway

**Comment by microbit-carlos** [comment]
Okay, converting the anchors into buttons should take advantage of the browser default A11y features, which is much better in general anyway.
I'm hoping this version works in all browsers.

**Comment by microbit-mark** [comment]
If we can use `<button>` then we also don't need the extra JS to check for enter/space key presses as it's built into `<button>`. I'll merge this and update my branch. Thanks 😄

**Comment by microbit-carlos** [comment]
> If we can use <button> then we also don't need the extra JS to check for enter/space key presses as it's built into <button>.

I _think_ in this case the JS is there to enable the click anywhere in the table row, so if it still works correctly with the button I would probably leave as it is.

**Comment by microbit-mark** [comment]
[Scratch to JS blocks https://github.com/microbit-foundation/microbit-support/issues/48](https://trello.com/c/tYFKnNF4/118-scratch-to-js-blocks-https-githubcom-microbit-foundation-microbit-support-issues-48)

**Pull request merged**
